---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Pull image
      docker_image:
        name: sm0223/calculator-junit-devops
        source: pull
    - name: Run container
      shell : docker run -it -d sm0223/calculator-junit-devops